Follow "Make it possible to set StyleGuideBaseURL per department"
Follow https://github.com/rubocop-hq/rubocop/pull/7295

This commit fixes the following error.

```console
% bundle exec rake
Files:           1
Modules:         3 (    3 undocumented)
Classes:         1 (    0 undocumented)
Constants:       1 (    1 undocumented)
Attributes:      0 (    0 undocumented)
Methods:         2 (    2 undocumented)
 14.29% documented
 rake aborted!
 ArgumentError: wrong number of arguments (given 3, expected 4)
 tasks/cops_documentation.rake:156:in `new'
 tasks/cops_documentation.rake:156:in `references'
 tasks/cops_documentation.rake:24:in `cops_body'
 tasks/cops_documentation.rake:197:in `print_cop_with_doc'
 tasks/cops_documentation.rake:173:in `block in
 print_cops_of_department'
 tasks/cops_documentation.rake:172:in `each'
 tasks/cops_documentation.rake:172:in `print_cops_of_department'
 tasks/cops_documentation.rake:268:in `block in main'
 tasks/cops_documentation.rake:267:in `each'
 tasks/cops_documentation.rake:267:in `main'
 tasks/cops_documentation.rake:278:in `block in <top (required)>'
 /Users/koic/.rbenv/versions/2.6.3/bin/bundle:23:in `load'
 /Users/koic/.rbenv/versions/2.6.3/bin/bundle:23:in `<main>'
 Tasks: TOP => default => generate_cops_documentation
 (See full trace by running task with --trace)
 ```