Apply some changelog format tests to changelog directory
This commit applies some changelog format tests to changelog directory
to prevent the following error when running `rake changelog:merge`.

```console
% bundle exec rake changelog:merge
rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass

  entry.match(/\. \((?<contributors>.+)\)\n/)[:contributors].split(',')
                                             ^^^^^^^^^^^^^^^
/Users/koic/src/github.com/rubocop/rubocop-minitest/tasks/changelog.rb:130:in `block in contributors'
/Users/koic/src/github.com/rubocop/rubocop-minitest/tasks/changelog.rb:129:in `each'
/Users/koic/src/github.com/rubocop/rubocop-minitest/tasks/changelog.rb:129:in `flat_map'
/Users/koic/src/github.com/rubocop/rubocop-minitest/tasks/changelog.rb:129:in `contributors'
/Users/koic/src/github.com/rubocop/rubocop-minitest/tasks/changelog.rb:123:in `new_contributor_lines'
/Users/koic/src/github.com/rubocop/rubocop-minitest/tasks/changelog.rb:105:in `merge_content'
/Users/koic/src/github.com/rubocop/rubocop-minitest/tasks/changelog.rb:94:in `merge!'
tasks/changelog.rake:21:in `block (2 levels) in <top (required)>'
/Users/koic/.rbenv/versions/3.1.2/bin/bundle:25:in `load'
/Users/koic/.rbenv/versions/3.1.2/bin/bundle:25:in `<main>'
Tasks: TOP => changelog:merge
(See full trace by running task with --trace)
```

This error occurs when there is no period in the changelog format. It is because the tests
applied to CHANGELOG.md were not applied to the changelog directory.