Fix an error for `Minitst/AssertOperator` and `Minitest/RefuteOperator`
This PR fixes the following error for `Minitst/AssertOperator` and `Minitest/RefuteOperator`
when running with Ruby 2.7:

```console
$ ruby -v
ruby 2.7.8p225 (2023-03-30 revision 1f4d455848) [x86_64-darwin19]

$ bundle exec rake

Finished in 2.522134s, 15.0666 runs/s, 18.6350 assertions/s.

  1) Error: RefuteOperatorTest#test_registers_offense_when_using_refute_with_operator_method_and_message:
FrozenError: can't modify frozen String: "expected, :<, actual"
    /Users/koic/src/github.com/rubocop/rubocop-minitest/lib/rubocop/cop/minitest/refute_operator.rb:46:
    in `build_new_arguments'
    /Users/koic/src/github.com/rubocop/rubocop-minitest/lib/rubocop/cop/minitest/refute_operator.rb:30:
    in `on_send'
```

And it introduces CI for the oldest RuboCop version still supported,
implementing a workflow for regression testing that is similar to the one found a
https://github.com/rubocop/rubocop-rails/commit/c9acb7a.